In [22]:
import numpy as np
np.random.seed(12345)

# Sampling

https://docs.scipy.org/doc/numpy-1.14.1/reference/routines.random.html

In [23]:
# Sample from array
x = np.array([1, 2, 3, 4, 5])
p = np.array([0.6, 0.1, 0.1, 0.1, 0.1])
sample = np.random.choice(a = x, size=20, replace=True, p=p)
sample

array([5, 1, 1, 1, 1, 1, 5, 2, 3, 2, 3, 5, 1, 1, 1, 2, 4, 4, 5, 3])

In [24]:
# Sample from normal
sample = np.random.normal(loc=0, scale=1, size=10)
sample

array([ 1.35291684,  0.88642934, -2.00163731, -0.37184254,  1.66902531,
       -0.43856974, -0.53974145,  0.47698501,  3.24894392, -1.02122752])

In [25]:
# Sample from uniform
sample = np.random.uniform(low=0, high=1, size=10)
sample

array([0.59636601, 0.05195755, 0.89508953, 0.72826618, 0.81835001,
       0.50022275, 0.81018941, 0.09596853, 0.21895004, 0.25871906])